
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import AuthProvider from '@/context/AuthProvider'
import { Toaster, toast } from 'sonner'
import "./globals.css";
import I18nProvider from "@/i18n/i18nProvider";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <I18nProvider>
            <Toaster richColors position="top-center" />
            {children}
          </I18nProvider>
        </AuthProvider>
      </body>
    </html>
  );
}



